<?php

/**
 * Implements hook_theme()
 */
function songs_theme(&$variables) {
  

    // $template = $this->twig->loadTemplate(
    //     drupal_get_path('module', 'songs') . '/templates/songs.html.twig'
    // );

    // $build = [
    //       'description' => [
    //       '#type' => 'inline_template',
    //       '#template' => file_get_contents($template),
    //     ]
    // ];

    // return $build;
}